# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install production dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm install --omit=dev --ignore-scripts

# Copy source code
COPY src ./src

# Create dist directory and build
RUN mkdir dist && npm run build

# The MCP uses stdio; no port to expose
CMD ["node", "dist/index.js"]
